### ISSUE TITLE
You should try hosting it on Github Pages if it's a portfolio

### ISSUE THREAD

**Issue by adeeb10abbas** [Sohan022/Portfolio#1]
https://pages.github.com/

**Comment by Sohan022** [comment]
Initially, I created a repo named Portfolio, in which I was writing my piece of code and push that code into the repo. After completing my all coding part then I hosted on Github page. Since I have a GitHub pro account, I took a free .tech domain.
Now, You can see my portfolio...

https://sohanlalgupta.tech
